### ISSUE TITLE
404 - Groceries Page

### ISSUE THREAD

**Issue by jessfeliciano** [jessfeliciano/SmartPrep#2]
Happens when visiting groceries page from top nav

<img width="1316" alt="Screen Shot 2023-08-23 at 12 45 52 PM" src="https://github.com/jessfeliciano/SmartPrep/assets/38792828/821a7607-f8a6-4928-870d-922f86f279bd">

Sometimes when navigating back to recipes page, a 404 is generated for that page:

<img width="1155" alt="Screen Shot 2023-08-23 at 12 47 18 PM" src="https://github.com/jessfeliciano/SmartPrep/assets/38792828/48dcbd10-c3f1-432e-aea5-0f8badaf80a6">

Not something that I can reproduce locally. Last deployment: https://vercel.com/jessfeliciano/smart-prep/rHYFTasnY6gBdSfeLbfMN2Ro5XgC

**Comment by Bolaji06** [comment]
Hello Jess, the issue for this bug might be that Vercel was unable to access the groceries file path. Make sure that the file path is in the built output of your deployment.

**Comment by jessfeliciano** [comment]
Can't 100% explain why the fix worked, but I switched from using `NavLink` instead of `a` tags for the internal links. 

As I understand it, NavLink should be used for internal links within an SPA it prevents a full page reload. Since I'm using React Router, NavLink leverages its mechanism so there's inherent benefit. 

I can imagine this is probably a best practice, so learned something new here.

**Comment by Bolaji06** [comment]
Glad you found a solution to the issue. Happy Coding Jess!
